CREATE TABLE Hotels (

Hotel_name VARCHAR ( 255 ) NOT NULL,

Hotel_stars SMALLINT NOT NULL,

CountGuests SMALLINT NOT NULL,

id_hotel SMALLINT NOT NULL,

id_kurort SMALLINT NOT NULL,

CONSTRAINT PK_Hotels20 PRIMARY KEY (id_hotel)

);

CREATE TABLE Client (

Surname VARCHAR ( 255 ) NOT NULL,

Name VARCHAR ( 255 ) NOT NULL,

Otchestvo VARCHAR ( 255 ) NOT NULL,

Birth_date VARCHAR ( 255 ) NOT NULL,

Passport_info VARCHAR ( 255 ) NOT NULL,

id_client SMALLINT NOT NULL,

CONSTRAINT PK_Client18 PRIMARY KEY (id_client)

);

CREATE TABLE Sales (

Cost_of_one SMALLINT NOT NULL,

Count SMALLINT NOT NULL,

id_sale SMALLINT NOT NULL,

id_client SMALLINT NOT NULL,

id_hotel SMALLINT NOT NULL,

id_turagen SMALLINT NOT NULL,

CONSTRAINT PK_Sales22 PRIMARY KEY (id_sale)

);

CREATE TABLE Turagenstvo (

Turag_name VARCHAR ( 255 ) NOT NULL,

id_turagen SMALLINT NOT NULL,

CONSTRAINT PK_Turagenstvo23 PRIMARY KEY (id_turagen)

);

CREATE TABLE Kurorts (

Kurort_name VARCHAR ( 255 ) NOT NULL,

Mid_temp SMALLINT NOT NULL,

id_kurort SMALLINT NOT NULL,

id_country SMALLINT NOT NULL,

CONSTRAINT PK_Kurorts21 PRIMARY KEY (id_kurort)

);

CREATE TABLE Countrys (

Country_name VARCHAR ( 255 ) NOT NULL,

id_country SMALLINT NOT NULL,

CONSTRAINT PK_Countrys19 PRIMARY KEY (id_country)

);

ALTER TABLE Hotels ADD CONSTRAINT FK_Hotels21 FOREIGN KEY (id_kurort) REFERENCES Kurorts (id_kurort) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Sales ADD CONSTRAINT FK_Sales20 FOREIGN KEY (id_hotel) REFERENCES Hotels (id_hotel) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Sales ADD CONSTRAINT FK_Sales18 FOREIGN KEY (id_client) REFERENCES Client (id_client) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Sales ADD CONSTRAINT FK_Sales22 FOREIGN KEY (id_turagen) REFERENCES Turagenstvo (id_turagen) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Kurorts ADD CONSTRAINT FK_Kurorts19 FOREIGN KEY (id_country) REFERENCES Countrys (id_country) ON DELETE NO ACTION ON UPDATE NO ACTION;